### ISSUE TITLE
CPAL

### ISSUE THREAD

**Issue by a8568730** [sih4sing5hong5/tai5-uan5_gian5-gi2_hok8-bu7#219]
參考reddit [LICENSE](https://github.com/reddit/reddit/blob/master/LICENSE)

You may obtain a copy of the License at _____________
You may obtain a copy of the License at http://code.reddit.com/LICENSE

The Original Code is______________________.
The Original Code is reddit

Graphic Image as provided in the Covered Code, if any.
Graphic Image as provided in the Covered Code:
http://code.reddit.com/reddit_logo.png

**Comment by sih4sing5hong5** [comment]
#220 做好矣
